"""create_initial_risk_tables

Revision ID: aee18c6aad26
Revises: 
Create Date: 2026-03-16 23:12:59.053039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aee18c6aad26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_profiles',
    sa.Column('account_id', sa.String(length=64), nullable=False, comment='Sender account ID — matches sender_id in transactions table'),
    sa.Column('total_txn_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='Total transactions ever submitted by this account'),
    sa.Column('total_volume_lifetime', sa.Numeric(precision=20, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Total amount transacted over account lifetime'),
    sa.Column('total_volume_30d', sa.Numeric(precision=20, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Total amount transacted in the last 30 days'),
    sa.Column('txn_count_30d', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Number of transactions in the last 30 days'),
    sa.Column('total_volume_24h', sa.Numeric(precision=20, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Total amount transacted in the last 24 hours'),
    sa.Column('txn_count_24h', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Number of transactions in the last 24 hours'),
    sa.Column('txn_count_1h', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Number of transactions in the last 1 hour — strongest velocity signal'),
    sa.Column('total_volume_1h', sa.Numeric(precision=20, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Total amount transacted in the last 1 hour'),
    sa.Column('avg_txn_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Running average transaction amount'),
    sa.Column('max_txn_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0.00'), nullable=False, comment='Largest single transaction ever submitted'),
    sa.Column('last_txn_amount', sa.Numeric(precision=20, scale=2), nullable=True, comment='Amount of the most recent transaction'),
    sa.Column('is_high_risk', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Manually or automatically flagged as high-risk account'),
    sa.Column('fraud_txn_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Number of transactions confirmed as fraud'),
    sa.Column('blocked_txn_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Number of transactions blocked by risk engine'),
    sa.Column('review_txn_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Number of transactions sent to manual review'),
    sa.Column('unique_receiver_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Number of distinct receiver accounts ever transacted with'),
    sa.Column('known_receiver_ids', postgresql.ARRAY(sa.String(length=64)), server_default=sa.text('ARRAY[]::varchar[]'), nullable=False, comment='Array of known receiver account IDs'),
    sa.Column('unique_device_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Number of distinct device fingerprints seen'),
    sa.Column('known_device_fingerprints', postgresql.ARRAY(sa.String(length=128)), server_default=sa.text('ARRAY[]::varchar[]'), nullable=False, comment='Array of known device fingerprints'),
    sa.Column('unique_country_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Number of distinct destination countries transacted to'),
    sa.Column('known_receiver_countries', postgresql.ARRAY(sa.String(length=2)), server_default=sa.text('ARRAY[]::varchar[]'), nullable=False, comment='Array of known receiver countries (ISO 3166-1 alpha-2)'),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False, comment='When this account first submitted a transaction'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp of most recent transaction'),
    sa.Column('window_reset_at_24h', sa.DateTime(timezone=True), nullable=True, comment='When the 24h rolling window was last reset'),
    sa.Column('window_reset_at_1h', sa.DateTime(timezone=True), nullable=True, comment='When the 1h rolling window was last reset'),
    sa.Column('profile_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary metadata — notes, manual review flags, etc.'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Optimistic locking version'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index('ix_account_profiles_created_at', 'account_profiles', ['first_seen_at'], unique=False)
    op.create_index('ix_account_profiles_fraud_txn_count', 'account_profiles', ['fraud_txn_count'], unique=False)
    op.create_index('ix_account_profiles_is_high_risk', 'account_profiles', ['is_high_risk'], unique=False)
    op.create_index('ix_account_profiles_last_seen_at', 'account_profiles', ['last_seen_at'], unique=False)
    op.create_index('ix_account_profiles_risk_velocity', 'account_profiles', ['is_high_risk', 'txn_count_1h'], unique=False)
    op.create_index('ix_account_profiles_total_txn_count', 'account_profiles', ['total_txn_count'], unique=False)
    op.create_index('ix_account_profiles_txn_count_1h', 'account_profiles', ['txn_count_1h'], unique=False)
    op.create_table('risk_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('sender_id', sa.String(length=64), nullable=True),
    sa.Column('receiver_id', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REVIEW', 'BLOCK', name='riskdecision'), nullable=False),
    sa.Column('confidence', sa.String(length=10), server_default=sa.text("'MEDIUM'"), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=False),
    sa.Column('triggered_rules', sa.JSON(), nullable=True),
    sa.Column('rule_flags', sa.JSON(), nullable=True),
    sa.Column('ml_anomaly_score', sa.Float(), nullable=True),
    sa.Column('ml_model_version', sa.String(length=50), nullable=True),
    sa.Column('ml_fallback_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ml_features_used', sa.JSON(), nullable=True),
    sa.Column('ml_latency_ms', sa.Float(), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('llm_risk_factors', sa.JSON(), nullable=True),
    sa.Column('llm_recommendation', sa.String(length=100), nullable=True),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('llm_fallback_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('llm_latency_ms', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_results_correlation_id', 'risk_results', ['correlation_id'], unique=False)
    op.create_index('ix_risk_results_decision', 'risk_results', ['decision'], unique=False)
    op.create_index('ix_risk_results_decision_evaluated', 'risk_results', ['decision', 'evaluated_at'], unique=False)
    op.create_index('ix_risk_results_evaluated_at', 'risk_results', ['evaluated_at'], unique=False)
    op.create_index('ix_risk_results_high_risk_only', 'risk_results', ['id'], unique=False, postgresql_where=sa.text("risk_level IN ('HIGH', 'CRITICAL')"))
    op.create_index(op.f('ix_risk_results_id'), 'risk_results', ['id'], unique=False)
    op.create_index('ix_risk_results_level_evaluated', 'risk_results', ['risk_level', 'evaluated_at'], unique=False)
    op.create_index('ix_risk_results_ml_model_version', 'risk_results', ['ml_model_version'], unique=False)
    op.create_index(op.f('ix_risk_results_risk_level'), 'risk_results', ['risk_level'], unique=False)
    op.create_index('ix_risk_results_risk_score', 'risk_results', ['risk_score'], unique=False)
    op.create_index(op.f('ix_risk_results_sender_id'), 'risk_results', ['sender_id'], unique=False)
    op.create_index(op.f('ix_risk_results_transaction_id'), 'risk_results', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_results_transaction_id'), table_name='risk_results')
    op.drop_index(op.f('ix_risk_results_sender_id'), table_name='risk_results')
    op.drop_index('ix_risk_results_risk_score', table_name='risk_results')
    op.drop_index(op.f('ix_risk_results_risk_level'), table_name='risk_results')
    op.drop_index('ix_risk_results_ml_model_version', table_name='risk_results')
    op.drop_index('ix_risk_results_level_evaluated', table_name='risk_results')
    op.drop_index(op.f('ix_risk_results_id'), table_name='risk_results')
    op.drop_index('ix_risk_results_high_risk_only', table_name='risk_results', postgresql_where=sa.text("risk_level IN ('HIGH', 'CRITICAL')"))
    op.drop_index('ix_risk_results_evaluated_at', table_name='risk_results')
    op.drop_index('ix_risk_results_decision_evaluated', table_name='risk_results')
    op.drop_index('ix_risk_results_decision', table_name='risk_results')
    op.drop_index('ix_risk_results_correlation_id', table_name='risk_results')
    op.drop_table('risk_results')
    op.drop_index('ix_account_profiles_txn_count_1h', table_name='account_profiles')
    op.drop_index('ix_account_profiles_total_txn_count', table_name='account_profiles')
    op.drop_index('ix_account_profiles_risk_velocity', table_name='account_profiles')
    op.drop_index('ix_account_profiles_last_seen_at', table_name='account_profiles')
    op.drop_index('ix_account_profiles_is_high_risk', table_name='account_profiles')
    op.drop_index('ix_account_profiles_fraud_txn_count', table_name='account_profiles')
    op.drop_index('ix_account_profiles_created_at', table_name='account_profiles')
    op.drop_table('account_profiles')
    # ### end Alembic commands ###
